apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kpn-stable
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kpn-app
        track: stable
        version: 1.0.0
    spec:
      containers:
        - name: kpn-stable
          image: yasirmehmood/stable
          ports:
            - name: http
              containerPort: 80
